name: Main Build

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  vm-job:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        framework: [net10.0,net48]
    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - 5432:5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password12!
          POSTGRES_DB: test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      cockroachdb:
        image: cockroachdb/cockroach:latest
        ports:
          - 26257:26257/tcp
        env:
          COCKROACH_ARGS: "start-single-node"
          COCKROACH_USER: postgres
          COCKROACH_PASSWORD: Password12!
          COCKROACH_DATABASE: test
        options: --health-cmd "curl -f http://localhost:8080/health?ready=1" --health-interval 10s --health-timeout 5s --health-retries 5
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433/tcp
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!
        options: --health-cmd "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Password12!' -Q 'SELECT 1' || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: Password12!
          MYSQL_DATABASE: test
        options: --health-cmd "mysqladmin ping -ppassword" --health-interval 10s --health-timeout 5s --health-retries 5
      oracle:
        image: gvenzl/oracle-free:slim-faststart
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: testuser
          APP_USER_PASSWORD: Password12!
        ports:
          - 1521:1521 # Expose the default Oracle port
        options: --health-cmd healthcheck.sh --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: .NET Build
        run: dotnet build Dapper.Database/Dapper.Database.csproj -c Release /p:GITHUB=true --no-restore
      - name: Dapper Database  ${{ matrix.framework }}
        run: dotnet test Dapper.Database.Tests/Dapper.Database.Tests.csproj -c Release -f  ${{ matrix.framework }} -p:GITHUB=true -p:TestTfmsInParallel=false
        env:
          MySqlConnectionString: Server=localhost;Port=3306;Uid=root;Pwd=Password12!;Database=test;Allow User Variables=true
          PostgresConnectionString: Server=localhost;Port=5432;Database=test;User Id=postgres;Password=Password12!;
          CockroachDbConnectionString: Server=localhost;Port=26257;Database=test;User Id=postgres;Password=Password12!;
          MsSqlServerConnectionString: Server=tcp:localhost,1433;Database=tempdb;User Id=sa;Password=Password12!;TrustServerCertificate=True;
          OracleConnectionString: Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=FREEPDB1)));User Id=testuser;Password=Password12!;
